name: page_inscription
description: Application de d'insciption pour API dolibarr

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.0-204.0.dev <4.0.0'


dependencies:
  flutter:
   sdk: flutter

  cupertino_icons: ^1.0.2
  simple_animations: ^4.1.0
  supercharged: ^2.1.1
  build_runner: ^2.1.11
  build_web_compilers: ^3.2.3
  pin_code_fields: ^7.4.0

dev_dependencies:
  flutter_test:
   sdk: flutter


  flutter_lints: ^2.0.0
  characters: ^1.2.0

flutter:


  uses-material-design: true


  assets:
    - Diere/Images/Logo_Dolibar.png


    - family: Itim
      fonts:
      - asset: Diere/police/Itim-Regular.ttf
